services:
  # --- RELATIONAL DATABASE ---
  scm_db:
    image: postgres:17-alpine
    container_name: scm_db
    restart: always
    environment:
      POSTGRES_DB: scm_db
      POSTGRES_USER: scm_user
      POSTGRES_PASSWORD: scm_user
    ports:
      - "5432:5432"
    volumes:
      - scm_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U scm_user -d scm_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- DATABASE pgAdmin GUI ---
  # Accessible at http://localhost:5050
  pgadmin:
    image: dpage/pgadmin4
    container_name: scm_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@scm.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      scm_db:
        condition: service_healthy

  # --- METRICS COLLECTION (PROMETHEUS) ---
  # Scraping data from Spring Boot Actuator
  prometheus:
    image: prom/prometheus:latest
    container_name: scm_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      - scm_db

  # --- VISUALIZATION (GRAFANA) ---
  # Accessible at http://localhost:3000 (User/Pass: admin/admin)
  grafana:
    image: grafana/grafana:latest
    container_name: scm_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  scm_postgres_data:
  prometheus_data:
  grafana_data: