services:
  # --- INVENTORY SERVICE DATABASE ---
  scm_db:
    image: postgres:17-alpine
    container_name: scm_db
    restart: always
    environment:
      POSTGRES_DB: scm_db
      POSTGRES_USER: scm_user
      POSTGRES_PASSWORD: scm_user
    ports:
      - "5434:5432"              # changed from 5432 to avoid conflict with local PG on my machine
    volumes:
      - scm_postgres_data:/var/lib/postgresql/data
      - ./docker/scm_db/V1__Schema.sql:/docker-entrypoint-initdb.d/01_schema.sql
      - ./docker/scm_db/V2__Data.sql:/docker-entrypoint-initdb.d/02_data.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U scm_user -d scm_db" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- ORDER SERVICE DATABASE ---
  ord_db:
    image: postgres:17-alpine
    container_name: ord_db
    restart: always
    environment:
      POSTGRES_DB: ord_db
      POSTGRES_USER: ord_user
      POSTGRES_PASSWORD: ord_user
    ports:
      - "5433:5432"
    volumes:
      - ord_postgres_data:/var/lib/postgresql/data
      - ./docker/ord_db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ord_user -d ord_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # --- EVENT BROKER (KAFKA) ---
  scm_kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: scm_kafka
    ports:
      - "9092:9092"
    environment:
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@localhost:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,EXTERNAL://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://scm_kafka:29092,EXTERNAL://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_DIRS: '/var/lib/kafka/data'
    volumes:
      - scm_kafka_data:/var/lib/kafka/data
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics --bootstrap-server localhost:29092 --list"]
      interval: 10s
      timeout: 10s
      retries: 5

  # --- KAFKA TOPIC INIT ---
  kafka-init:
    image: confluentinc/cp-kafka:7.5.0
    container_name: scm_kafka_init
    depends_on:
      scm_kafka:
        condition: service_healthy
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        kafka-topics --bootstrap-server scm_kafka:29092 --create --if-not-exists --topic order-events --partitions 3 --replication-factor 1
        kafka-topics --bootstrap-server scm_kafka:29092 --create --if-not-exists --topic inventory-events --partitions 3 --replication-factor 1
        echo 'Kafka topics created successfully'
    restart: on-failure

  # --- DATABASE pgAdmin GUI ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: scm_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@scm.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      scm_db:
        condition: service_healthy
      ord_db:
        condition: service_healthy

  # --- METRICS COLLECTION (PROMETHEUS) ---
  prometheus:
    image: prom/prometheus:latest
    container_name: scm_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    depends_on:
      scm_db:
        condition: service_healthy
      ord_db:
        condition: service_healthy
      scm_kafka:
        condition: service_healthy

  # --- VISUALIZATION (GRAFANA) ---
  grafana:
    image: grafana/grafana:latest
    container_name: scm_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  scm_postgres_data:
  ord_postgres_data:
  scm_kafka_data:
  prometheus_data:
  grafana_data: