spring.application.name=SCM
spring.profiles.active=dev
# application.properties (shared)
spring.threads.virtual.enabled=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.consumer.group-id=scm-main-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
server.error.include-message=always
server.error.include-binding-errors=always


spring.datasource.hikari.leakDetectionThreshold=10000


# Expose the prometheus endpoint over the web
management.endpoints.web.exposure.include=health,metrics,info,prometheus

# Optional: Enable the prometheus endpoint specifically
management.endpoint.prometheus.enabled=true

# Optional: If you want to see all available metrics for debugging
management.metrics.export.prometheus.enabled=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE



# ----------------------------------------------------
# NATIVE GRAPHQL PLAYGROUND CONFIGURATION
# ----------------------------------------------------
# 1. Ensure the web-based development interface is explicitly turned on
spring.graphql.graphiql.enabled=true

# 2. CHANGE THIS line to point to the endpoint you are trying to reach (/sandbox)
spring.graphql.graphiql.path=/graphiql

# 3. Keep your base engine endpoint handling incoming data queries as /graphql
spring.graphql.path=/graphql

# 4. Leave your debugging levels active so we can catch any underlying schema errors
spring.graphql.schema.inspection.enabled=true
logging.level.org.springframework.graphql=DEBUG

