spring.application.name=SCM
spring.profiles.active=dev
# application.properties (shared)
spring.threads.virtual.enabled=true
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.acks=all
spring.kafka.producer.retries=3
spring.kafka.consumer.group-id=scm-main-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
server.error.include-message=always
server.error.include-binding-errors=always


# Expose the prometheus endpoint over the web
management.endpoints.web.exposure.include=health,info,prometheus

# Optional: Enable the prometheus endpoint specifically
management.endpoint.prometheus.enabled=true

# Optional: If you want to see all available metrics for debugging
management.metrics.export.prometheus.enabled=true

logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE