# Overrides
spring.main.allow-bean-definition-overriding=true
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jooq.JooqAutoConfiguration
spring.threads.virtual.enabled=false

# Inventory Domain (jOOQ)
spring.datasource.inventory.url=jdbc:h2:mem:inventory;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.inventory.driver-class-name=org.h2.Driver
spring.datasource.inventory.username=sa
spring.datasource.inventory.password=

# Order Domain (JPA & ShedLock)
spring.datasource.order.url=jdbc:h2:mem:order;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.order.driver-class-name=org.h2.Driver
spring.datasource.order.username=sa
spring.datasource.order.password=

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# Kafka (Mocking for tests)
spring.kafka.bootstrap-servers=localhost:9092